name = "remix-cloudflare-workers"
type = "javascript"
compatibility_date = "2022-08-30"

account_id = "e57808d9c904411a5df0d3557354fa09"
workers_dev = true
main = "./build/index.js"

[site]
bucket = "./public"

[build]
command = "npm run build"

[vars]
SUPABASE_URL="https://vmlkhepmwzyptrioibnh.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtbGtoZXBtd3p5cHRyaW9pYm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTY2MzY2NjcsImV4cCI6MTk3MjIxMjY2N30.cnaYcdvnGhFhWkLf5wdn6FZiKeRfbDhNit8JCEOanB4"
STRIPE_PUBLIC_KEY="pk_test_51LOATIBZScCwTRRkqrNqyzkpcNtNvNgGmzx2Gp1iFnnRdbV03GY1hd1fpifmQrJZAMSLII4gJ7IZaDeSRYh9qOIr00UcsopjC4"
